development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: MMS
  pool: 5
  username: root
  password: "colen12"
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: MMS_test
  pool: 5
  username: root
  password: "colen12"
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000